---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - satisfactory.pc-ziegert.de
  resources:
  - factoryservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - satisfactory.pc-ziegert.de
  resources:
  - factoryservers/finalizers
  verbs:
  - update
- apiGroups:
  - satisfactory.pc-ziegert.de
  resources:
  - factoryservers/status
  verbs:
  - get
  - patch
  - update
